// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: matchbox/storage/storagepb/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Group selects one or more machines and matches them to a Profile.
type Group struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// machine readable Id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// human readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Profile id
	Profile string `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	// Selectors to match machines
	Selector map[string]string `protobuf:"bytes,4,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// JSON encoded metadata
	Metadata      []byte `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_matchbox_storage_storagepb_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_matchbox_storage_storagepb_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_matchbox_storage_storagepb_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Group) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Group) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Profile defines the boot and provisioning behavior of a group of machines.
type Profile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// profile id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// human readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// ignition id
	IgnitionId string `protobuf:"bytes,3,opt,name=ignition_id,json=ignitionId,proto3" json:"ignition_id,omitempty"`
	// cloud config id
	CloudId string `protobuf:"bytes,4,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	// Types that are valid to be assigned to BootMode:
	//
	//	*Profile_Boot
	//	*Profile_Chain
	BootMode isProfile_BootMode `protobuf_oneof:"boot_mode"`
	// generic config id
	GenericId     string `protobuf:"bytes,6,opt,name=generic_id,json=genericId,proto3" json:"generic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_matchbox_storage_storagepb_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_matchbox_storage_storagepb_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_matchbox_storage_storagepb_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetIgnitionId() string {
	if x != nil {
		return x.IgnitionId
	}
	return ""
}

func (x *Profile) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *Profile) GetBootMode() isProfile_BootMode {
	if x != nil {
		return x.BootMode
	}
	return nil
}

func (x *Profile) GetBoot() *NetBoot {
	if x != nil {
		if x, ok := x.BootMode.(*Profile_Boot); ok {
			return x.Boot
		}
	}
	return nil
}

func (x *Profile) GetChain() string {
	if x != nil {
		if x, ok := x.BootMode.(*Profile_Chain); ok {
			return x.Chain
		}
	}
	return ""
}

func (x *Profile) GetGenericId() string {
	if x != nil {
		return x.GenericId
	}
	return ""
}

type isProfile_BootMode interface {
	isProfile_BootMode()
}

type Profile_Boot struct {
	// support network boot / PXE
	Boot *NetBoot `protobuf:"bytes,5,opt,name=boot,proto3,oneof"`
}

type Profile_Chain struct {
	// the url of the next bootloader
	Chain string `protobuf:"bytes,7,opt,name=chain,proto3,oneof"`
}

func (*Profile_Boot) isProfile_BootMode() {}

func (*Profile_Chain) isProfile_BootMode() {}

// NetBoot describes network or PXE boot settings for a machine.
type NetBoot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the URL of the kernel image
	Kernel string `protobuf:"bytes,1,opt,name=kernel,proto3" json:"kernel,omitempty"`
	// the init RAM filesystem URLs
	Initrd []string `protobuf:"bytes,2,rep,name=initrd,proto3" json:"initrd,omitempty"`
	// kernel args
	Args          []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetBoot) Reset() {
	*x = NetBoot{}
	mi := &file_matchbox_storage_storagepb_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetBoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetBoot) ProtoMessage() {}

func (x *NetBoot) ProtoReflect() protoreflect.Message {
	mi := &file_matchbox_storage_storagepb_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetBoot.ProtoReflect.Descriptor instead.
func (*NetBoot) Descriptor() ([]byte, []int) {
	return file_matchbox_storage_storagepb_storage_proto_rawDescGZIP(), []int{2}
}

func (x *NetBoot) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *NetBoot) GetInitrd() []string {
	if x != nil {
		return x.Initrd
	}
	return nil
}

func (x *NetBoot) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_matchbox_storage_storagepb_storage_proto protoreflect.FileDescriptor

const file_matchbox_storage_storagepb_storage_proto_rawDesc = "" +
	"\n" +
	"(matchbox/storage/storagepb/storage.proto\x12\tstoragepb\"\xda\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x12:\n" +
	"\bselector\x18\x04 \x03(\v2\x1e.storagepb.Group.SelectorEntryR\bselector\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\fR\bmetadata\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vignition_id\x18\x03 \x01(\tR\n" +
	"ignitionId\x12\x19\n" +
	"\bcloud_id\x18\x04 \x01(\tR\acloudId\x12(\n" +
	"\x04boot\x18\x05 \x01(\v2\x12.storagepb.NetBootH\x00R\x04boot\x12\x16\n" +
	"\x05chain\x18\a \x01(\tH\x00R\x05chain\x12\x1d\n" +
	"\n" +
	"generic_id\x18\x06 \x01(\tR\tgenericIdB\v\n" +
	"\tboot_mode\"\\\n" +
	"\aNetBoot\x12\x16\n" +
	"\x06kernel\x18\x01 \x01(\tR\x06kernel\x12\x16\n" +
	"\x06initrd\x18\x02 \x03(\tR\x06initrd\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04argsJ\x04\b\x03\x10\x04R\acmdlineB9Z7github.com/aalaesar/matchbox/matchbox/storage/storagepbb\x06proto3"

var (
	file_matchbox_storage_storagepb_storage_proto_rawDescOnce sync.Once
	file_matchbox_storage_storagepb_storage_proto_rawDescData []byte
)

func file_matchbox_storage_storagepb_storage_proto_rawDescGZIP() []byte {
	file_matchbox_storage_storagepb_storage_proto_rawDescOnce.Do(func() {
		file_matchbox_storage_storagepb_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchbox_storage_storagepb_storage_proto_rawDesc), len(file_matchbox_storage_storagepb_storage_proto_rawDesc)))
	})
	return file_matchbox_storage_storagepb_storage_proto_rawDescData
}

var file_matchbox_storage_storagepb_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_matchbox_storage_storagepb_storage_proto_goTypes = []any{
	(*Group)(nil),   // 0: storagepb.Group
	(*Profile)(nil), // 1: storagepb.Profile
	(*NetBoot)(nil), // 2: storagepb.NetBoot
	nil,             // 3: storagepb.Group.SelectorEntry
}
var file_matchbox_storage_storagepb_storage_proto_depIdxs = []int32{
	3, // 0: storagepb.Group.selector:type_name -> storagepb.Group.SelectorEntry
	2, // 1: storagepb.Profile.boot:type_name -> storagepb.NetBoot
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_matchbox_storage_storagepb_storage_proto_init() }
func file_matchbox_storage_storagepb_storage_proto_init() {
	if File_matchbox_storage_storagepb_storage_proto != nil {
		return
	}
	file_matchbox_storage_storagepb_storage_proto_msgTypes[1].OneofWrappers = []any{
		(*Profile_Boot)(nil),
		(*Profile_Chain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchbox_storage_storagepb_storage_proto_rawDesc), len(file_matchbox_storage_storagepb_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchbox_storage_storagepb_storage_proto_goTypes,
		DependencyIndexes: file_matchbox_storage_storagepb_storage_proto_depIdxs,
		MessageInfos:      file_matchbox_storage_storagepb_storage_proto_msgTypes,
	}.Build()
	File_matchbox_storage_storagepb_storage_proto = out.File
	file_matchbox_storage_storagepb_storage_proto_goTypes = nil
	file_matchbox_storage_storagepb_storage_proto_depIdxs = nil
}
